package quizz.avec.toto;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author victor
 */
public class Quizz_avec_toto extends javax.swing.JFrame {

    /**
     * Creates new form Quizz_avec_toto
     */
    public Quizz_avec_toto() {
        initComponents();
        LabelBonneRep.setVisible(false);
        LabelMauvaiseRep.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question1 = new javax.swing.JLabel();
        Enonce = new javax.swing.JLabel();
        BoutonMauvaiseRep2 = new javax.swing.JButton();
        BoutonMauvaiseRep1 = new javax.swing.JButton();
        BoutonBonneRep = new javax.swing.JButton();
        LabelBonneRep = new javax.swing.JLabel();
        LabelMauvaiseRep = new javax.swing.JLabel();

        question1.setText("Première question :");

        Enonce.setText("Combien Pierre mesure-t-il d'iPhone ?");

        BoutonMauvaiseRep2.setText("23 iPhone");
        BoutonMauvaiseRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMauvaiseRep2ActionPerformed(evt);
            }
        });

        BoutonMauvaiseRep1.setText("18 iPhone");
        BoutonMauvaiseRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMauvaiseRep1ActionPerformed(evt);
            }
        });

        BoutonBonneRep.setText("14 iPhone");
        BoutonBonneRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonBonneRepActionPerformed(evt);
            }
        });

        LabelBonneRep.setText("Bonne réponse !");

        LabelMauvaiseRep.setText("Mauvaise réponse !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Enonce)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(question1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(BoutonBonneRep)
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelMauvaiseRep)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelBonneRep)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BoutonMauvaiseRep1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(BoutonMauvaiseRep2)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(question1)
                .addGap(18, 18, 18)
                .addComponent(Enonce)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonMauvaiseRep1)
                    .addComponent(BoutonBonneRep)
                    .addComponent(BoutonMauvaiseRep2))
                .addGap(36, 36, 36)
                .addComponent(LabelBonneRep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelMauvaiseRep)
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonBonneRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonBonneRepActionPerformed
LabelBonneRep.setVisible(true);    // TODO add your handling code here:
LabelMauvaiseRep.setVisible(false);
    }//GEN-LAST:event_BoutonBonneRepActionPerformed

    private void BoutonMauvaiseRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMauvaiseRep1ActionPerformed
LabelMauvaiseRep.setVisible(true);        // TODO add your handling code here:
LabelBonneRep.setVisible(false);
    }//GEN-LAST:event_BoutonMauvaiseRep1ActionPerformed

    private void BoutonMauvaiseRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMauvaiseRep2ActionPerformed
LabelMauvaiseRep.setVisible(true);        // TODO add your handling code here:
LabelBonneRep.setVisible(false);
    }//GEN-LAST:event_BoutonMauvaiseRep2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonBonneRep;
    private javax.swing.JButton BoutonMauvaiseRep1;
    private javax.swing.JButton BoutonMauvaiseRep2;
    private javax.swing.JLabel Enonce;
    private javax.swing.JLabel LabelBonneRep;
    private javax.swing.JLabel LabelMauvaiseRep;
    private javax.swing.JLabel question1;
    // End of variables declaration//GEN-END:variables
}
